import React,{useEffect,useRef,useState} from 'react';
import {sections,techniques,habits,sleep,books} from './content';
import './source.css';
const number=i=>String(i+1).padStart(2,'0');
function Picture({name,alt}){return <figure className="article-illustration"><img src={`/assets/${name}.jpg`} alt={alt} width="1200" height="800" loading="lazy"/></figure>}
function Section({id,title,children}){return <section className="article-section" id={`lag-${id}`} tabIndex={-1}>{title&&<h2>{title}</h2>}{children}</section>}
export function App(){
 const [menu,setMenu]=useState(false),[progress,setProgress]=useState(0),[active,setActive]=useState('beginning');
 const toggle=useRef(null),nav=useRef(null);
 useEffect(()=>{let frame;const update=()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>{const max=document.documentElement.scrollHeight-innerHeight;setProgress(max>0?Math.min(100,Math.max(0,scrollY/max*100)):0);let current='beginning';for(const[id]of sections){if(document.getElementById(`lag-${id}`)?.getBoundingClientRect().top<160)current=id;}setActive(current)})};addEventListener('scroll',update,{passive:true});addEventListener('resize',update);update();return()=>{cancelAnimationFrame(frame);removeEventListener('scroll',update);removeEventListener('resize',update)}},[]);
 useEffect(()=>{if(!menu)return;const old=document.body.style.overflow;document.body.style.overflow='hidden';nav.current?.querySelector('button')?.focus();const key=e=>{if(e.key==='Escape'){setMenu(false);toggle.current?.focus()}if(e.key==='Tab'){const els=nav.current.querySelectorAll('a,button'),first=els[0],last=els[els.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}};addEventListener('keydown',key);return()=>{document.body.style.overflow=old;removeEventListener('keydown',key)}},[menu]);
 const links=()=> <ol>{sections.map(([id,label])=><li key={id}><a href={`#lag-${id}`} aria-current={active===id?'true':undefined} onClick={()=>{setMenu(false);requestAnimationFrame(()=>document.getElementById(`lag-${id}`)?.focus({preventScroll:true}))}}>{label}</a></li>)}</ol>;
 return <div id="lag"><a className="skip-link" href="#lag-article">Перейти к статье</a><div className="reading-progress" role="progressbar" aria-label="Прогресс чтения" aria-valuemin={0} aria-valuemax={100} aria-valuenow={Math.round(progress)}><span style={{width:`${progress}%`}}/></div>
 <button ref={toggle} className="mobile-nav-toggle" aria-label={menu?'Закрыть меню разделов':'Открыть меню разделов'} aria-expanded={menu} aria-controls="guide-menu" onClick={()=>setMenu(!menu)}><span className="mobile-nav-icon" aria-hidden="true"><i/><i/><i/></span><span>Разделы</span></button><div className={`mobile-nav-backdrop ${menu?'visible':''}`} onClick={()=>setMenu(false)}/><nav ref={nav} className={`mobile-nav ${menu?'visible':''}`} id="guide-menu" aria-label="Разделы гайда" aria-hidden={!menu} inert={!menu?true:undefined}><div className="mobile-nav-head"><strong>Разделы гайда</strong><button className="mobile-nav-close" aria-label="Закрыть меню" onClick={()=>{setMenu(false);toggle.current?.focus()}}>×</button></div>{links()}</nav>
 <header className="site-header"><div className="container header-inner"><span className="header-label">Спокойнее • Бережное знакомство с тревогой</span></div></header><main id="lag-top">
 <section className="hero" aria-labelledby="guide-title"><div className="container hero-grid"><div className="hero-copy"><p className="eyebrow">Понятный гайд о тревоге</p><h1 id="guide-title">Тревога: как её понять и <em>найти свою опору</em></h1><p className="hero-lead">Мысли возвращаются к одному и тому же, трудно уснуть, а тело будто всё время настороже? С тревогой сталкиваются многие. Здесь можно разобраться в своих ощущениях и найти небольшие шаги, которые помогут поддержать себя — сейчас и в повседневной жизни.</p><div className="hero-note"><strong>Объяснения, практики и бережный подход к себе</strong></div><div className="hero-actions"><a className="button" href="#lag-now">Мне тревожно сейчас</a><a className="button secondary" href="#lag-article">Разобраться в причинах</a></div></div><div className="hero-visual" aria-hidden="true"><div className="hero-image-frame"><img src="/assets/hero.jpg" alt="" fetchPriority="high"/></div><div className="hero-visual-card"><strong>Больше опоры внутри</strong><span>Начните с одного небольшого шага.</span></div></div></div></section>
 <section className="routes container" aria-labelledby="routes-title"><div className="route-panel"><div className="route-panel-head"><h2 id="routes-title">С чего хочется начать?</h2><p>Читайте последовательно или выберите свой раздел</p></div><div className="route-grid">{[['now','Тревожно прямо сейчас','8 способов поддержать себя'],['background','Напряжение не отпускает','Привычки для повседневной опоры'],['sleep','Сложно успокоиться вечером','Небольшой маршрут перед сном']].map(([id,h,p],i)=><a className="route-card" href={`#lag-${id}`} key={id}><span className="route-icon">{number(i)}</span><span><strong>{h}</strong><small>{p}</small></span><span className="route-arrow" aria-hidden="true">→</span></a>)}</div></div></section>
 <div className="container reading-layout" id="lag-article" tabIndex={-1}><aside className="toc-wrap"><nav className="toc" aria-label="Оглавление"><p className="toc-title">Внутри гайда</p>{links()}<p className="toc-time">Не обязательно читать всё за один раз. Возвращайтесь к нужным разделам в своём темпе.</p></nav></aside><article className="article">
 <Section id="beginning"><p className="lead-paragraph dropcap">Иногда вокруг спокойно, а внутри всё ещё продолжается напряжённый день.</p><p>Вы перебираете возможные ошибки, готовитесь к завтрашним разговорам или чувствуете беспокойство без ясной причины. Такое состояние может утомлять, даже когда со стороны ничего особенного не происходит.</p><p>Здесь собраны объяснения и способы самоподдержки. Выбирайте то, что вам подходит, и не требуйте от себя немедленного результата.</p><h2>Откуда берётся тревога</h2><p>Тревога связана с ожиданием возможной угрозы. Она помогает обращать внимание на неопределённость, готовиться к сложным ситуациям и искать решения. Перед важным событием некоторое волнение вполне обычно.</p><p>Но ожидание опасности иногда становится слишком настойчивым. Вместо одного плана появляются десятки сценариев, а попытка предусмотреть всё не приносит облегчения.</p><p>На тревогу могут влиять нагрузка, недосып, пережитые события, состояние здоровья и особенности привычного мышления. У разных людей сочетание причин различается.</p><p>Первый шаг — замечать, когда возникает напряжение, что ему предшествует и как вы на него отвечаете. Это наблюдение, а не повод обвинять себя.</p><Picture name="alarm" alt="Иллюстрация: тревожные сигналы в спокойной обстановке"/></Section>
 <Section id="fear" title="Тревога и страх: что их отличает"><p>Эти переживания похожи, но внимание в них направлено немного по-разному.</p><p><strong>Страх</strong> чаще связан с заметной угрозой в настоящем: например, рядом резко затормозила машина. Ситуация требует реакции прямо сейчас.</p><p><strong>Тревога</strong> часто обращена в будущее: «А если что-то случится?» Событие ещё не произошло, но вы уже чувствуете напряжение и пытаетесь подготовиться.</p><p>Граница между ними не всегда чёткая. Важнее понять, что происходит и какая поддержка нужна вам в данный момент.</p></Section>
 <Section id="body" title="Почему откликается тело"><p>При тревоге могут меняться дыхание и сердцебиение, усиливаться потливость, появляться дрожь и напряжение мышц. Иногда человек сначала замечает ощущения в теле и только затем понимает, что волнуется.</p><p>Это может пугать и запускать новый круг беспокойства. Полезно обращать внимание на удобное положение тела, спокойное окружение и комфортное дыхание.</p><div className="callout clay"><p><strong>Не списывайте любые симптомы на тревогу.</strong>Новые, выраженные или необычные ощущения стоит обсудить с врачом. При сильной боли в груди, выраженной нехватке воздуха или потере сознания нужна срочная медицинская помощь.</p></div></Section>
 <Section id="cost" title="Когда беспокойство занимает слишком много места"><p>Ориентиром может быть не только сила переживания, но и то, насколько оно мешает обычной жизни.</p><div className="impact-grid">{[['Сон','Трудно переключиться с размышлений на отдых. Засыпание затягивается, а утром не хватает сил.'],['Самочувствие','Длительное напряжение утомляет. Становится сложнее сосредоточиться и восстанавливаться.'],['Общение','Хочется чаще перепроверять, искать заверения или избегать разговоров, которые вызывают волнение.'],['Решения','Даже небольшие задачи откладываются, потому что хочется сначала обрести полную уверенность.'],['Повседневные радости','Внимание возвращается к возможным проблемам. На интересные и приятные занятия остаётся меньше места.']].map(([h,p])=><div className="impact-item" key={h}><strong>{h}</strong><p>{p}</p></div>)}</div></Section>
 <Section id="not-dangerous" title="Не обязательно бороться с каждым ощущением"><p>Попытка запретить себе тревожиться может добавлять раздражение: «Почему я опять не справляюсь?» Попробуйте заметить состояние и назвать его без оценки.</p><p>Можно испытывать тревогу и одновременно делать небольшие полезные действия. Не нужно заставлять себя терпеть чрезмерный дискомфорт или отказываться от помощи.</p><div className="personal-story"><p>«Сейчас я замечаю тревогу. Мне не нужно решать всё сразу. Я могу выбрать один посильный шаг и обратиться за поддержкой».</p><footer>Фраза для самоподдержки</footer></div></Section>
 <Section id="now" title="Если тревожно прямо сейчас"><p className="lead-paragraph">Выберите один способ. Попробуйте его спокойно и оцените, подходит ли он вам.</p><Picture name="grounding" alt="Иллюстрация: спокойное дыхание и ощущение опоры под ногами"/><div className="technique-grid">{techniques.map(([h,p],i)=><div className={`technique ${i===0?'featured':''}`} key={h}><span className="technique-number">{i===0?'1–5':number(i)}</span><div><h3>{h}</h3><p>{p}</p></div></div>)}</div><small className="micro-note">Если упражнение усиливает головокружение или дискомфорт, остановитесь. Описание мягкого дыхания опирается на <a href="https://www.nhs.uk/mental-health/self-help/guides-tools-and-activities/breathing-exercises-for-stress/" target="_blank" rel="noreferrer">рекомендации NHS</a>.</small></Section>
 <Section id="background" title="Опора в повседневных привычках"><p>Когда напряжение возвращается изо дня в день, одной практики в моменте может быть мало. Полезно посмотреть на нагрузку, отдых и привычные реакции на беспокойство.</p><p>Начните с одного небольшого изменения, которое вписывается в вашу жизнь.</p><Picture name="rituals" alt="Дневник и чашка у окна в тёплом утреннем свете"/><div className="habit-list">{habits.map(([h,p],i)=><details className="habit" key={h} open={i===0?true:undefined}><summary><span className="habit-index">{number(i)}</span><span>{h}</span></summary><div className="habit-body"><p>{p}</p></div></details>)}</div></Section>
 <Section id="sleep" title="Как сделать вечер спокойнее"><p>В тишине незавершённые дела могут становиться заметнее. Появляется желание срочно всё обдумать — именно тогда, когда хочется отдохнуть.</p><p>Попробуйте составить простой вечерний порядок. Он не гарантирует быстрое засыпание, но может помочь перейти от дел к отдыху.</p><div className="sleep-plan">{sleep.map(([h,p])=><div className="sleep-step" key={h}><div><h3>{h}</h3><p>{p}</p></div></div>)}</div></Section>
 <Section id="owner"><div className="manifesto"><h2>В жизни может быть больше опоры</h2><div className="manifesto-lines"><span>Вам не нужно становиться человеком, который никогда не волнуется.</span><strong>Можно учиться заботиться о себе, даже когда тревога рядом.</strong></div></div><p className="after-manifesto">Изменения не всегда идут по прямой. Иногда знакомая практика помогает, иногда хочется выбрать другую или обратиться к специалисту. Это не обнуляет предыдущие шаги.</p><p>Замечайте не только интенсивность тревоги, но и то, что вы смогли сделать для себя сегодня.</p></Section>
 <Section id="books" title="Книги для знакомства с темой"><p>Если хочется продолжить чтение, можно начать с одной книги. Это дополнительный материал, а не замена индивидуальной помощи.</p><div className="books">{books.map(([h,p],i)=><div className="book" key={h}><span className="book-index">{number(i)}</span><div><h3>{h}</h3><p>{p}</p></div></div>)}</div></Section>
 <Section id="about" title="Когда стоит обратиться за поддержкой"><p>Если тревога регулярно мешает спать, работать, общаться или выходить из дома, стоит обсудить это с квалифицированным специалистом. Обращаться можно и раньше — не обязательно ждать, пока станет совсем тяжело.</p><p>Расскажите, как давно появилось беспокойство, когда оно усиливается и что вы уже пробовали. Врач поможет оценить симптомы и возможные причины, а психологическую помощь можно подобрать с учётом вашей ситуации.</p><div className="callout"><p><strong>Поддержка начинается с разговора.</strong>Можно заранее записать вопросы и попросить близкого помочь с поиском специалиста. Вы не обязаны разбираться во всём самостоятельно.</p></div></Section>
 </article></div><section className="next-steps"><div className="container"><div className="next-head"><p className="eyebrow">Ваш следующий шаг</p><h2>Начните с того, что посильно сегодня</h2><p>Не все практики нужны сразу. Выберите одну точку опоры.</p></div><div className="choice-grid"><div className="choice product"><span className="choice-label">Здесь и сейчас</span><h3>Небольшая пауза<br/>для себя</h3><p>Вернитесь к практикам и выберите наиболее удобную.</p><ul><li>устроиться в комфортном положении</li><li>заметить окружающие предметы</li><li>дать дыханию идти спокойно</li><li>попросить близкого побыть рядом</li></ul><a className="button" href="#lag-now">Выбрать практику</a></div><div className="choice"><span className="choice-label">В своём темпе</span><h3>Больше устойчивости<br/>в обычном дне</h3><p>Какое небольшое изменение сделало бы день чуть легче?</p><ul><li>выделить время для отдыха</li><li>снизить поток уведомлений</li><li>заметить повторяющиеся переживания</li><li>обсудить трудности со специалистом</li></ul><a className="button secondary" href="#lag-background">Перейти к привычкам</a></div></div></div></section></main>
 <footer className="site-footer"><div className="container"><p>Образовательный материал. Не заменяет диагностику, лечение или экстренную помощь. Если есть непосредственная угроза жизни или риск причинить вред себе, обратитесь в местную экстренную службу.</p><p>Спокойнее · 2026</p></div></footer><a className={`back-to-top ${progress>3?'visible':''}`} href="#lag-top" aria-label="Вернуться наверх"><span aria-hidden="true">↑</span>Наверх</a></div>
}
